ci: Reorganize test declarations and dependencies.
Signed-off-by: Jason Volk <jason@zemos.net>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -317,6 +317,111 @@ jobs:
       includes: ${{inputs.includes}}
       checkout: ${{inputs.checkout}}
 
+  mas:
+    if: >
+      !failure() && !cancelled()
+      && fromJSON(inputs.enable_mas)
+      && !contains(inputs.pipeline, '[ci no build]')
+      && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
+      && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
+      && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
+
+    name: MAS
+    uses: ./.github/workflows/bake.yml
+    with:
+      bake_targets: '["mas-testee"]'
+      cargo_profiles: '["bench"]'
+      feat_sets: '["logging"]'
+      rust_toolchains: '["nightly"]'
+      sys_names: ${{inputs.sys_names}}
+      sys_versions: ${{inputs.sys_versions}}
+      rust_targets: ${{inputs.rust_targets}}
+      sys_targets: '["x86_64-v3-linux-gnu"]'
+      machines: ${{inputs.machines}}
+      runner: ${{inputs.complement_runner}}
+      excludes: ${{inputs.excludes}}
+      includes: ${{inputs.includes}}
+      checkout: ${{inputs.checkout}}
+
+  playwright:
+    if: >
+      !failure() && !cancelled()
+      && fromJSON(inputs.enable_playwright)
+      && !contains(inputs.pipeline, '[ci no build]')
+      && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
+      && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
+      && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
+
+    name: Playwright
+    uses: ./.github/workflows/bake.yml
+    with:
+      bake_targets: '["playwright-tester", "playwright-testee"]'
+      cargo_profiles: '["bench"]'
+      feat_sets: '["logging"]'
+      rust_toolchains: '["nightly"]'
+      sys_names: ${{inputs.sys_names}}
+      sys_versions: ${{inputs.sys_versions}}
+      rust_targets: ${{inputs.rust_targets}}
+      sys_targets: '["x86_64-v3-linux-gnu"]'
+      machines: ${{inputs.machines}}
+      runner: ${{inputs.playwright_runner}}
+      excludes: ${{inputs.excludes}}
+      includes: ${{inputs.includes}}
+      checkout: ${{inputs.checkout}}
+
+  complement:
+    if: >
+      !failure() && !cancelled()
+      && fromJSON(inputs.enable_complement)
+      && !contains(inputs.pipeline, '[ci no build]')
+      && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
+      && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
+      && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
+
+    name: Complement
+    uses: ./.github/workflows/bake.yml
+    with:
+      bake_targets: '["complement-tester", "complement-testee"]'
+      cargo_profiles: '["bench"]'
+      feat_sets: '["logging"]'
+      rust_toolchains: '["nightly"]'
+      sys_names: ${{inputs.sys_names}}
+      sys_versions: ${{inputs.sys_versions}}
+      rust_targets: ${{inputs.rust_targets}}
+      sys_targets: '["x86_64-v3-linux-gnu"]'
+      machines: ${{inputs.machines}}
+      runner: ${{inputs.complement_runner}}
+      excludes: ${{inputs.excludes}}
+      includes: ${{inputs.includes}}
+      checkout: ${{inputs.checkout}}
+
+  complement-crypto:
+    if: >
+      !failure() && !cancelled()
+      && fromJSON(inputs.enable_complement)
+      && fromJSON(inputs.enable_complement_crypto)
+      && !contains(inputs.pipeline, '[ci no build]')
+      && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
+      && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
+      && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
+
+    name: Complement-Crypto
+    uses: ./.github/workflows/bake.yml
+    with:
+      bake_targets: '["complement-crypto-tester", "complement-testee"]'
+      cargo_profiles: '["bench"]'
+      feat_sets: '["logging"]'
+      rust_toolchains: '["nightly"]'
+      sys_names: ${{inputs.sys_names}}
+      sys_versions: ${{inputs.sys_versions}}
+      rust_targets: ${{inputs.rust_targets}}
+      sys_targets: '["x86_64-v3-linux-gnu"]'
+      machines: ${{inputs.machines}}
+      runner: ${{inputs.complement_runner}}
+      excludes: ${{inputs.excludes}}
+      includes: ${{inputs.includes}}
+      checkout: ${{inputs.checkout}}
+
   rust-sdk-integ:
     if: >
       !failure() && !cancelled()
@@ -327,7 +432,6 @@ jobs:
       && contains(fromJSON(inputs.rust_targets), fromJSON('["x86_64-unknown-linux-gnu"]')[0])
 
     name: Matrix SDK Integration
-    needs: [doc, unit, bench, memcheck, smoke, nix]
     uses: ./.github/workflows/bake.yml
     with:
       #bake_targets: '["rust-sdk-integ", "rust-sdk-valgrind"]'
@@ -370,19 +474,51 @@ jobs:
           {"sys_target": "aarch64-v8-linux-gnu"},
         ]
 
-  complement:
+  acceptance-init:
     if: >
       !failure() && !cancelled()
-      && fromJSON(inputs.enable_complement)
+      && fromJSON(inputs.enable_playwright)
       && !contains(inputs.pipeline, '[ci no build]')
+      && inputs.machines
       && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
       && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
       && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
 
-    name: Complement
-    uses: ./.github/workflows/bake.yml
+    runs-on: ["${{fromJSON(inputs.machines)[0]}}", "${{inputs.playwright_runner}}"]
+
+    outputs:
+      ids: ${{steps.gen.outputs.ids}}
+
+    steps:
+    - id: gen
+      name: Generate Shard Matrix
+      env:
+        shards: ${{inputs.playwright_shards}}
+      run: |
+        case "$shards" in ''|*[!0-9]*) echo "invalid shards: '$shards'" >&2; exit 1;; esac
+        test "$shards" -ge 1 || { echo "shards must be >= 1" >&2; exit 1; }
+        echo "ids=[$(seq -s, 1 "$shards")]" >> "$GITHUB_OUTPUT"
+
+  acceptance:
+    if: >
+      !failure() && !cancelled()
+      && fromJSON(inputs.enable_playwright)
+      && !contains(inputs.pipeline, '[ci no build]')
+      && inputs.machines
+      && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
+      && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
+      && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
+
+    name: Acceptance (element-web)
+    needs: [playwright, acceptance-init]
+    uses: ./.github/workflows/acceptance.yml
     with:
-      bake_targets: '["complement-tester", "complement-testee"]'
+      job_name: Acceptance (element-web)
+      runner: ${{inputs.playwright_runner}}
+      workers: ${{inputs.playwright_workers}}
+      retries: ${{inputs.playwright_retries}}
+      shards: ${{inputs.playwright_shards}}
+      shard_ids: ${{needs.acceptance-init.outputs.ids}}
       cargo_profiles: '["bench"]'
       feat_sets: '["logging"]'
       rust_toolchains: '["nightly"]'
@@ -391,7 +527,46 @@ jobs:
       rust_targets: ${{inputs.rust_targets}}
       sys_targets: '["x86_64-v3-linux-gnu"]'
       machines: ${{inputs.machines}}
+      excludes: ${{inputs.excludes}}
+      includes: ${{inputs.includes}}
+      checkout: ${{inputs.checkout}}
+
+  authentication:
+    if: >
+      !failure() && !cancelled()
+      && fromJSON(inputs.enable_mas)
+      && !contains(inputs.pipeline, '[ci no build]')
+      && inputs.machines
+      && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
+      && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
+      && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
+
+    name: Authentication (MAS)
+    needs: [mas]
+
+    uses: ./.github/workflows/compliance.yml
+    with:
+      job_name: Authentication (MAS)
+      flavor: mas
       runner: ${{inputs.complement_runner}}
+      script: docker/mas.sh
+      summariser: .github/workflows/mas_summarise.sh
+      results_path: tests/mas/results.jsonl
+      logs_path: tests/mas/tuwunel.log
+      runtime_metrics_path: tests/mas/mas.log
+      verbose: ${{inputs.mas_verbose}}
+      results_artifact_prefix: mas_results
+      output_artifact_prefix: mas_output
+      metrics_artifact_prefix: mas_worker_log
+      runtime_history: false
+      cargo_profiles: '["bench"]'
+      feat_sets: '["logging"]'
+      rust_toolchains: '["nightly"]'
+      sys_names: ${{inputs.sys_names}}
+      sys_versions: ${{inputs.sys_versions}}
+      rust_targets: ${{inputs.rust_targets}}
+      sys_targets: '["x86_64-v3-linux-gnu"]'
+      machines: ${{inputs.machines}}
       excludes: ${{inputs.excludes}}
       includes: ${{inputs.includes}}
       checkout: ${{inputs.checkout}}
@@ -407,7 +582,7 @@ jobs:
       && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
 
     name: Compliance (tuwunel)
-    needs: [doc, unit, bench, memcheck, smoke, nix, complement]
+    needs: [complement]
 
     uses: ./.github/workflows/compliance.yml
     with:
@@ -436,73 +611,6 @@ jobs:
       includes: ${{inputs.includes}}
       checkout: ${{inputs.checkout}}
 
-  compliance-interop:
-    if: >
-      !failure() && !cancelled()
-      && fromJSON(inputs.enable_complement)
-      && fromJSON(inputs.enable_complement_interop)
-      && !contains(inputs.pipeline, '[ci no build]')
-      && inputs.machines
-      && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
-      && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
-      && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
-
-    name: Interoperability (${{inputs.complement_interop_peer}})
-    needs: [doc, unit, bench, memcheck, smoke, nix, complement]
-
-    uses: ./.github/workflows/compliance.yml
-    with:
-      job_name: Interoperability (${{inputs.complement_interop_peer}})
-      flavor: complement
-      runner: ${{inputs.complement_runner}}
-      script: interop=${{inputs.complement_interop_peer}} docker/complement.sh "${{inputs.complement_interop_run}}"
-      summariser: .github/workflows/complement_interop_summarise.sh
-      results_path: tests/complement/interop/results.jsonl
-      logs_path: tests/complement/interop/logs.jsonl
-      runtime_metrics_path: tests/complement/interop/runtime_metrics.tar.zst
-      verbose: ${{inputs.complement_interop_verbose}}
-      results_artifact_prefix: complement_interop_results
-      output_artifact_prefix: complement_interop_output
-      metrics_artifact_prefix: complement_interop_runtime_metrics
-      cargo_profiles: '["bench"]'
-      feat_sets: '["logging"]'
-      rust_toolchains: '["nightly"]'
-      sys_names: ${{inputs.sys_names}}
-      sys_versions: ${{inputs.sys_versions}}
-      rust_targets: ${{inputs.rust_targets}}
-      sys_targets: '["x86_64-v3-linux-gnu"]'
-      machines: ${{inputs.machines}}
-      excludes: ${{inputs.excludes}}
-      includes: ${{inputs.includes}}
-      checkout: ${{inputs.checkout}}
-
-  complement-crypto:
-    if: >
-      !failure() && !cancelled()
-      && fromJSON(inputs.enable_complement)
-      && fromJSON(inputs.enable_complement_crypto)
-      && !contains(inputs.pipeline, '[ci no build]')
-      && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
-      && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
-      && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
-
-    name: Complement-Crypto
-    uses: ./.github/workflows/bake.yml
-    with:
-      bake_targets: '["complement-crypto-tester", "complement-testee"]'
-      cargo_profiles: '["bench"]'
-      feat_sets: '["logging"]'
-      rust_toolchains: '["nightly"]'
-      sys_names: ${{inputs.sys_names}}
-      sys_versions: ${{inputs.sys_versions}}
-      rust_targets: ${{inputs.rust_targets}}
-      sys_targets: '["x86_64-v3-linux-gnu"]'
-      machines: ${{inputs.machines}}
-      runner: ${{inputs.complement_runner}}
-      excludes: ${{inputs.excludes}}
-      includes: ${{inputs.includes}}
-      checkout: ${{inputs.checkout}}
-
   compliance-crypto:
     if: >
       !failure() && !cancelled()
@@ -515,7 +623,7 @@ jobs:
       && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
 
     name: Cryptography (rust-sdk)
-    needs: [doc, unit, bench, memcheck, smoke, nix, complement-crypto]
+    needs: [complement-crypto]
 
     uses: ./.github/workflows/compliance.yml
     with:
@@ -543,117 +651,34 @@ jobs:
       includes: ${{inputs.includes}}
       checkout: ${{inputs.checkout}}
 
-  playwright:
+  compliance-interop:
     if: >
       !failure() && !cancelled()
-      && fromJSON(inputs.enable_playwright)
-      && !contains(inputs.pipeline, '[ci no build]')
-      && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
-      && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
-      && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
-
-    name: Playwright
-    uses: ./.github/workflows/bake.yml
-    with:
-      bake_targets: '["playwright-tester", "playwright-testee"]'
-      cargo_profiles: '["bench"]'
-      feat_sets: '["logging"]'
-      rust_toolchains: '["nightly"]'
-      sys_names: ${{inputs.sys_names}}
-      sys_versions: ${{inputs.sys_versions}}
-      rust_targets: ${{inputs.rust_targets}}
-      sys_targets: '["x86_64-v3-linux-gnu"]'
-      machines: ${{inputs.machines}}
-      runner: ${{inputs.playwright_runner}}
-      excludes: ${{inputs.excludes}}
-      includes: ${{inputs.includes}}
-      checkout: ${{inputs.checkout}}
-
-  acceptance:
-    if: >
-      !failure() && !cancelled()
-      && fromJSON(inputs.enable_playwright)
+      && fromJSON(inputs.enable_complement)
+      && fromJSON(inputs.enable_complement_interop)
       && !contains(inputs.pipeline, '[ci no build]')
       && inputs.machines
       && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
       && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
       && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
 
-    name: Acceptance (element-web)
-    needs: [doc, unit, bench, memcheck, smoke, nix, playwright]
-    uses: ./.github/workflows/acceptance.yml
-    with:
-      job_name: Acceptance (element-web)
-      runner: ${{inputs.playwright_runner}}
-      workers: ${{inputs.playwright_workers}}
-      retries: ${{inputs.playwright_retries}}
-      shards: ${{inputs.playwright_shards}}
-      cargo_profiles: '["bench"]'
-      feat_sets: '["logging"]'
-      rust_toolchains: '["nightly"]'
-      sys_names: ${{inputs.sys_names}}
-      sys_versions: ${{inputs.sys_versions}}
-      rust_targets: ${{inputs.rust_targets}}
-      sys_targets: '["x86_64-v3-linux-gnu"]'
-      machines: ${{inputs.machines}}
-      excludes: ${{inputs.excludes}}
-      includes: ${{inputs.includes}}
-      checkout: ${{inputs.checkout}}
-
-  mas:
-    if: >
-      !failure() && !cancelled()
-      && fromJSON(inputs.enable_mas)
-      && !contains(inputs.pipeline, '[ci no build]')
-      && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
-      && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
-      && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
-
-    name: MAS
-    uses: ./.github/workflows/bake.yml
-    with:
-      bake_targets: '["mas-testee"]'
-      cargo_profiles: '["bench"]'
-      feat_sets: '["logging"]'
-      rust_toolchains: '["nightly"]'
-      sys_names: ${{inputs.sys_names}}
-      sys_versions: ${{inputs.sys_versions}}
-      rust_targets: ${{inputs.rust_targets}}
-      sys_targets: '["x86_64-v3-linux-gnu"]'
-      machines: ${{inputs.machines}}
-      runner: ${{inputs.complement_runner}}
-      excludes: ${{inputs.excludes}}
-      includes: ${{inputs.includes}}
-      checkout: ${{inputs.checkout}}
-
-  authentication:
-    if: >
-      !failure() && !cancelled()
-      && fromJSON(inputs.enable_mas)
-      && !contains(inputs.pipeline, '[ci no build]')
-      && inputs.machines
-      && contains(fromJSON(inputs.cargo_profiles), fromJSON('["bench"]')[0])
-      && contains(fromJSON(inputs.rust_toolchains), fromJSON('["nightly"]')[0])
-      && contains(fromJSON(inputs.sys_targets), fromJSON('["x86_64-v3-linux-gnu"]')[0])
-
-    name: Authentication (MAS)
-    needs: [doc, unit, bench, memcheck, smoke, nix, mas]
+    name: Interoperability (${{inputs.complement_interop_peer}})
+    needs: [complement]
 
     uses: ./.github/workflows/compliance.yml
     with:
-      job_name: Authentication (MAS)
-      flavor: mas
+      job_name: Interoperability (${{inputs.complement_interop_peer}})
+      flavor: complement
       runner: ${{inputs.complement_runner}}
-      script: docker/mas.sh
-      summariser: .github/workflows/mas_summarise.sh
-      results_path: tests/mas/results.jsonl
-      logs_path: tests/mas/tuwunel.log
-      runtime_metrics_path: tests/mas/mas.log
-      verbose: ${{inputs.mas_verbose}}
-      results_artifact_prefix: mas_results
-      output_artifact_prefix: mas_output
-      metrics_artifact_prefix: mas_worker_log
-      runtime_history: false
+      script: interop=${{inputs.complement_interop_peer}} docker/complement.sh "${{inputs.complement_interop_run}}"
+      summariser: .github/workflows/complement_interop_summarise.sh
+      results_path: tests/complement/interop/results.jsonl
+      logs_path: tests/complement/interop/logs.jsonl
+      runtime_metrics_path: tests/complement/interop/runtime_metrics.tar.zst
+      verbose: ${{inputs.complement_interop_verbose}}
+      results_artifact_prefix: complement_interop_results
+      output_artifact_prefix: complement_interop_output
+      metrics_artifact_prefix: complement_interop_runtime_metrics
       cargo_profiles: '["bench"]'
       feat_sets: '["logging"]'
       rust_toolchains: '["nightly"]'
